config/routes.rb
Rails.application.routes.draw do
  resources :vessels
  resources :charactersheets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "main_page#index"

  get "/avery", to: "avery#index"
  get "/phearon", to: "phearon#index"
  get "/roberts", to: "roberts#index"
  get "/feargus", to: "feargus#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/charactersheet.rb
class Charactersheet < ApplicationRecord
end

app/models/vessel.rb
class Vessel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/avery_controller.rb
class AveryController < ApplicationController
  #before_action :set_charactersheet, only: %i[ show edit update destroy ]
  def index

  end

  def get

  end
end

app/controllers/charactersheets_controller.rb
class CharactersheetsController < ApplicationController
  before_action :set_charactersheet, only: %i[ show edit update destroy ]

  # GET /charactersheets or /charactersheets.json
  def index
    @charactersheets = Charactersheet.all
  end

  # GET /charactersheets/1 or /charactersheets/1.json
  def show
  end

  # GET /charactersheets/new
  def new
    @charactersheet = Charactersheet.new
  end

  # GET /charactersheets/1/edit
  def edit
  end

  # POST /charactersheets or /charactersheets.json
  def create
    @charactersheet = Charactersheet.new(charactersheet_params)

    respond_to do |format|
      if @charactersheet.save
        format.html { redirect_to @charactersheet, notice: "Charactersheet was successfully created." }
        format.json { render :show, status: :created, location: @charactersheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @charactersheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charactersheets/1 or /charactersheets/1.json
  def update
    respond_to do |format|
      if @charactersheet.update(charactersheet_params)
        format.html { redirect_to @charactersheet, notice: "Charactersheet was successfully updated." }
        format.json { render :show, status: :ok, location: @charactersheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @charactersheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charactersheets/1 or /charactersheets/1.json
  def destroy
    @charactersheet.destroy!

    respond_to do |format|
      format.html { redirect_to charactersheets_path, status: :see_other, notice: "Charactersheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charactersheet
      @charactersheet = Charactersheet.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def charactersheet_params
      params.expect(charactersheet: [ :name ])
    end
end

app/controllers/feargus_controller.rb
class FeargusController < ApplicationController
  #before_action :set_charactersheet, only: %i[ show edit update destroy ]
  def index

  end

  def get

  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
    def index
        #render(MainPage::MainPageComponent.new())
    end
end

app/controllers/phearon_controller.rb
class PhearonController < ApplicationController
  #before_action :set_charactersheet, only: %i[ show edit update destroy ]
  def index

  end

  def get

  end
end

app/controllers/roberts_controller.rb
class RobertsController < ApplicationController
  #before_action :set_charactersheet, only: %i[ show edit update destroy ]
  def index

  end

  def get

  end
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: %i[ show edit update destroy ]

  # GET /vessels or /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/1 or /vessels/1.json
  def show
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels or /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to @vessel, notice: "Vessel was successfully created." }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1 or /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to @vessel, notice: "Vessel was successfully updated." }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1 or /vessels/1.json
  def destroy
    @vessel.destroy!

    respond_to do |format|
      format.html { redirect_to vessels_path, status: :see_other, notice: "Vessel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def vessel_params
      params.expect(vessel: [ :name, :type, :complement, :propulsion, :maneuverablility, :size, :seaworthiness, :shiphandling, :overall_ac, :hull_sections, :sink, :section_hp, :section_ac, :rigging_sections, :rigging_hp, :ram, :mounts, :space, :height, :watch, :complement, :speed, :cost, :rowers ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charactersheets_helper.rb
module CharactersheetsHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/avery/index.html.erb
<h1>Avery</h1>

app/views/charactersheets/_charactersheet.html.erb
<div id="<%= dom_id charactersheet %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= charactersheet.name %>
  </p>

</div>

app/views/charactersheets/_form.html.erb
<%= form_with(model: charactersheet, class: "contents") do |form| %>
  <% if charactersheet.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(charactersheet.errors.count, "error") %> prohibited this charactersheet from being saved:</h2>

      <ul>
        <% charactersheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/charactersheets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing charactersheet</h1>

  <%= render "form", charactersheet: @charactersheet %>

  <%= link_to "Show this charactersheet", @charactersheet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to charactersheets", charactersheets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/charactersheets/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Charactersheets" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Charactersheets</h1>
    <%= link_to "New charactersheet", new_charactersheet_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="charactersheets" class="min-w-full">
    <% @charactersheets.each do |charactersheet| %>
      <%= render charactersheet %>
      <p>
        <%= link_to "Show this charactersheet", charactersheet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/charactersheets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New charactersheet</h1>

  <%= render "form", charactersheet: @charactersheet %>

  <%= link_to "Back to charactersheets", charactersheets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/charactersheets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @charactersheet %>

    <%= link_to "Edit this charactersheet", edit_charactersheet_path(@charactersheet), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to charactersheets", charactersheets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this charactersheet", @charactersheet, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/feargus/index.html.erb
<h1>Feargus</h1>
<p>This page serves as a calculator for homebrew/complex stats</p>

<h2>Emberland Msp</h2>

<h2>Army Game</h2>

app/views/main_page/index.html.erb
<h1>Main Page</h1>

app/views/phearon/index.html.erb
<h1>Phearon</h1>
<p>This page serves as a calculator for homebrew/complex stats</p>

<h2>Gear calculator</h2>

<h2>Assassins Roster</h2>

app/views/roberts/index.html.erb
<h1>Roberts</h1>
<p>This page serves as a calculator for homebrew/complex stats</p>

<h2>Crew Effects</h2>

<h2>Ships</h2>

<h2>Ship Game</h2>

app/views/vessels/_form.html.erb
<%= form_with(model: vessel, class: "contents") do |form| %>
  <% if vessel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
        <% vessel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :type %>
    <%= form.text_field :type, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :complement %>
    <%= form.text_field :complement, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :propulsion %>
    <%= form.text_field :propulsion, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :maneuverablility %>
    <%= form.text_field :maneuverablility, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :size %>
    <%= form.text_field :size, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :seaworthiness %>
    <%= form.number_field :seaworthiness, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :shiphandling %>
    <%= form.number_field :shiphandling, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :overall_ac %>
    <%= form.number_field :overall_ac, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :hull_sections %>
    <%= form.number_field :hull_sections, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sink %>
    <%= form.number_field :sink, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :section_hp %>
    <%= form.number_field :section_hp, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :section_ac %>
    <%= form.number_field :section_ac, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rigging_sections %>
    <%= form.number_field :rigging_sections, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rigging_hp %>
    <%= form.number_field :rigging_hp, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ram %>
    <%= form.text_field :ram, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :mounts %>
    <%= form.number_field :mounts, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :space %>
    <%= form.text_field :space, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :height %>
    <%= form.text_field :height, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :watch %>
    <%= form.number_field :watch, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :complement %>
    <%= form.number_field :complement, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :speed %>
    <%= form.number_field :speed, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost %>
    <%= form.number_field :cost, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rowers %>
    <%= form.number_field :rowers, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/vessels/_vessel.html.erb
<div id="<%= dom_id vessel %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= vessel.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= vessel.vessel_type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Complement:</strong>
    <%= vessel.complement %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Propulsion:</strong>
    <%= vessel.propulsion %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Maneuverablility:</strong>
    <%= vessel.maneuverablility %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Size:</strong>
    <%= vessel.size %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Seaworthiness:</strong>
    <%= vessel.seaworthiness %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Shiphandling:</strong>
    <%= vessel.shiphandling %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Overall ac:</strong>
    <%= vessel.overall_ac %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hull sections:</strong>
    <%= vessel.hull_sections %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Sink:</strong>
    <%= vessel.sink %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Section hp:</strong>
    <%= vessel.section_hp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Section ac:</strong>
    <%= vessel.section_ac %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rigging sections:</strong>
    <%= vessel.rigging_sections %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rigging hp:</strong>
    <%= vessel.rigging_hp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ram:</strong>
    <%= vessel.ram %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Mounts:</strong>
    <%= vessel.mounts %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Space:</strong>
    <%= vessel.space %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Height:</strong>
    <%= vessel.height %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Watch:</strong>
    <%= vessel.watch %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Complement:</strong>
    <%= vessel.complement %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Speed:</strong>
    <%= vessel.speed %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cost:</strong>
    <%= vessel.cost %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rowers:</strong>
    <%= vessel.rowers %>
  </p>

</div>

app/views/vessels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing vessel</h1>

  <%= render "form", vessel: @vessel %>

  <%= link_to "Show this vessel", @vessel, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to vessels", vessels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vessels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Vessels" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Vessels</h1>
    <%= link_to "New vessel", new_vessel_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="vessels" class="min-w-full">
    <% @vessels.each do |vessel| %>
      <%= render vessel %>
      <p>
        <%= link_to "Show this vessel", vessel, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/vessels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New vessel</h1>

  <%= render "form", vessel: @vessel %>

  <%= link_to "Back to vessels", vessels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vessels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @vessel %>

    <%= link_to "Edit this vessel", edit_vessel_path(@vessel), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to vessels", vessels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this vessel", @vessel, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>